### ISSUE TITLE
Inaccurate version bounds in  .cabal file and/or compile error with GHC 8.0

### ISSUE THREAD

**Issue by hvr** [haskell-works/hw-prim#5]
as can be seen on http://matrix.hackage.haskell.org/package/hw-prim the upper bounds in `hw-prim.cabal` appear inaccurate. With GHC 8.0 there's a compile failure:

```
Preprocessing library hw-prim-0.0.0.12...
[ 1 of 11] Compiling HaskellWorks.Data.Vector.StorableVectorLike ( src/HaskellWorks/Data/Vector/StorableVectorLike.hs, /tmp/hw-prim-0.0.0.12/dist-newstyle/build/hw-prim-0.0.0.12/build/HaskellWorks/Data/Vector/StorableVectorLike.o )

src/HaskellWorks/Data/Vector/StorableVectorLike.hs:14:3-68: error:
    • Could not deduce (StorableVectorLike v e0)
      from the context: (StorableVectorLike v e, Storable a, Storable b)
        bound by the type signature for:
                   sImap :: (StorableVectorLike v e, Storable a, Storable b) =>
                            (Int -> a -> b) -> v a -> v b
        at src/HaskellWorks/Data/Vector/StorableVectorLike.hs:14:3-68
      The type variable ‘e0’ is ambiguous
    • In the ambiguity check for ‘sImap’
      To defer the ambiguity check to use sites, enable AllowAmbiguousTypes
      When checking the class method:
        sImap :: forall (v :: * -> *) e.
                 StorableVectorLike v e =>
                 forall a b.
                 (Storable a, Storable b) =>
                 (Int -> a -> b) -> v a -> v b
      In the class declaration for ‘StorableVectorLike’

src/HaskellWorks/Data/Vector/StorableVectorLike.hs:15:3-60: error:
    • Could not deduce (StorableVectorLike v e0)
      from the context: (StorableVectorLike v e, Storable a, Storable b)
        bound by the type signature for:
                   sMap :: (StorableVectorLike v e, Storable a, Storable b) =>
                           (a -> b) -> v a -> v b
        at src/HaskellWorks/Data/Vector/StorableVectorLike.hs:15:3-60
      The type variable ‘e0’ is ambiguous
    • In the ambiguity check for ‘sMap’
      To defer the ambiguity check to use sites, enable AllowAmbiguousTypes
      When checking the class method:
        sMap :: forall (v :: * -> *) e.
                StorableVectorLike v e =>
                forall a b. (Storable a, Storable b) => (a -> b) -> v a -> v b
      In the class declaration for ‘StorableVectorLike’

src/HaskellWorks/Data/Vector/StorableVectorLike.hs:16:3-61: error:
    • Could not deduce (StorableVectorLike v e0)
      from the context: (StorableVectorLike v e, Storable a)
        bound by the type signature for:
                   sUnfoldr :: (StorableVectorLike v e, Storable a) =>
                               (b -> Maybe (a, b)) -> b -> v a
        at src/HaskellWorks/Data/Vector/StorableVectorLike.hs:16:3-61
      The type variable ‘e0’ is ambiguous
    • In the ambiguity check for ‘sUnfoldr’
      To defer the ambiguity check to use sites, enable AllowAmbiguousTypes
      When checking the class method:
        sUnfoldr :: forall (v :: * -> *) e.
                    StorableVectorLike v e =>
                    forall a b. Storable a => (b -> Maybe (a, b)) -> b -> v a
      In the class declaration for ‘StorableVectorLike’

src/HaskellWorks/Data/Vector/StorableVectorLike.hs:17:3-69: error:
    • Could not deduce (StorableVectorLike v e0)
      from the context: (StorableVectorLike v e, Storable a)
        bound by the type signature for:
                   sUnfoldrN :: (StorableVectorLike v e, Storable a) =>
                                Int -> (b -> Maybe (a, b)) -> b -> v a
        at src/HaskellWorks/Data/Vector/StorableVectorLike.hs:17:3-69
      The type variable ‘e0’ is ambiguous
    • In the ambiguity check for ‘sUnfoldrN’
      To defer the ambiguity check to use sites, enable AllowAmbiguousTypes
      When checking the class method:
        sUnfoldrN :: forall (v :: * -> *) e.
                     StorableVectorLike v e =>
                     forall a b. Storable a => Int -> (b -> Maybe (a, b)) -> b -> v a
      In the class declaration for ‘StorableVectorLike’
```

**Comment by newhoggy** [comment]
Thanks.  I will look into this.

**Comment by newhoggy** [comment]
It's not clear to me how to fix this.  Any documentation I can look at to learn more about it?

**Comment by newhoggy** [comment]
So far my dependencies haven't been building:

```
[nix-shell:~/wrk/haskell-works/hw-all/hw-prim]$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.0.20160411
[nix-shell:~/wrk/haskell-works/hw-all/hw-prim]$ mafia build
Writing a default package environment file to
/Users/jky/wrk/haskell-works/hw-all/hw-prim/cabal.sandbox.config
Creating a new sandbox at
/Users/jky/wrk/haskell-works/hw-all/hw-prim/.cabal-sandbox/8.0.0.20160411
Installing dependencies...
Creating sandbox for vector-th-unbox-0.2.1.6-8e146e7c83bb8edcaa204ad481dff5ee2f6d99d6
Waiting for vector-th-unbox-0.2.1.6-8e146e7c83bb8edcaa204ad481dff5ee2f6d99d6
Creating sandbox for mwc-random-0.13.4.0-630a95e0827291abb0c1d105db23a0f142c62ed7
Waiting for mwc-random-0.13.4.0-630a95e0827291abb0c1d105db23a0f142c62ed7
Building vector-th-unbox-0.2.1.6-8e146e7c83bb8edcaa204ad481dff5ee2f6d99d6Building mwc-random-0.13.4.0-630a95e0827291abb0c1d105db23a0f142c62ed7

Resolving dependencies...
Resolving dependencies...
Notice: installing into a sandbox located at
/Users/jky/.ambiata/mafia/packages/1/8.0.0.20160411/mwc-random-0.13.4.0-630a95e0827291abb0c1d105db23a0f142c62ed7
Configuring mwc-random-0.13.4.0...
Notice: installing into a sandbox located at
/Users/jky/.ambiata/mafia/packages/1/8.0.0.20160411/vector-th-unbox-0.2.1.6-8e146e7c83bb8edcaa204ad481dff5ee2f6d99d6
Configuring vector-th-unbox-0.2.1.6...
Building mwc-random-0.13.4.0...
Building vector-th-unbox-0.2.1.6...
Failed to install vector-th-unbox-0.2.1.6
Build log ( /Users/jky/.ambiata/mafia/packages/1/8.0.0.20160411/vector-th-unbox-0.2.1.6-8e146e7c83bb8edcaa204ad481dff5ee2f6d99d6/logs/vector-th-unbox-0.2.1.6.log ):
Configuring vector-th-unbox-0.2.1.6...
Building vector-th-unbox-0.2.1.6...
Preprocessing library vector-th-unbox-0.2.1.6...
[1 of 1] Compiling Data.Vector.Unboxed.Deriving ( Data/Vector/Unboxed/Deriving.hs, dist/dist-sandbox-49a7d904/build/Data/Vector/Unboxed/Deriving.o )

Data/Vector/Unboxed/Deriving.hs:132:27: error:
    • Couldn't match expected type ‘[Dec] -> Dec’
                  with actual type ‘Dec’
    • The first argument of ($) takes one argument,
      but its type ‘Dec’ has none
      In the expression:
        InstanceD
          Nothing cxts (ConT ''M.MVector `AppT` ConT ''MVector `AppT` typ)
        $ concat
            [wrap 'M.basicLength [mv] id,
             wrap 'M.basicUnsafeSlice [i, n, ....] (AppE mvCon),
             wrap 'M.basicOverlaps [mv, mv'] id,
             wrap 'M.basicUnsafeNew [n] (liftE mvCon), ....]
      In an equation for ‘instanceMVector’:
          instanceMVector
            = InstanceD
                Nothing cxts (ConT ''M.MVector `AppT` ConT ''MVector `AppT` typ)
              $ concat
                  [wrap 'M.basicLength [mv] id,
                   wrap 'M.basicUnsafeSlice [i, ....] (AppE mvCon),
                   wrap 'M.basicOverlaps [mv, ....] id, ....]

Data/Vector/Unboxed/Deriving.hs:132:37: error:
    • Couldn't match type ‘Maybe a0’ with ‘[Pred]’
      Expected type: Cxt
        Actual type: Maybe a0
    • In the first argument of ‘InstanceD’, namely ‘Nothing’
      In the expression:
        InstanceD
          Nothing cxts (ConT ''M.MVector `AppT` ConT ''MVector `AppT` typ)
      In the expression:
        InstanceD
          Nothing cxts (ConT ''M.MVector `AppT` ConT ''MVector `AppT` typ)
        $ concat
            [wrap 'M.basicLength [mv] id,
             wrap 'M.basicUnsafeSlice [i, n, ....] (AppE mvCon),
             wrap 'M.basicOverlaps [mv, mv'] id,
             wrap 'M.basicUnsafeNew [n] (liftE mvCon), ....]

Data/Vector/Unboxed/Deriving.hs:132:45: error:
    • Couldn't match type ‘[Pred]’ with ‘Type’
      Expected type: Type
        Actual type: Cxt
    • In the second argument of ‘InstanceD’, namely ‘cxts’
      In the expression:
        InstanceD
          Nothing cxts (ConT ''M.MVector `AppT` ConT ''MVector `AppT` typ)
      In the expression:
        InstanceD
          Nothing cxts (ConT ''M.MVector `AppT` ConT ''MVector `AppT` typ)
        $ concat
            [wrap 'M.basicLength [mv] id,
             wrap 'M.basicUnsafeSlice [i, n, ....] (AppE mvCon),
             wrap 'M.basicOverlaps [mv, mv'] id,
             wrap 'M.basicUnsafeNew [n] (liftE mvCon), ....]

Data/Vector/Unboxed/Deriving.hs:133:14: error:
    • Couldn't match expected type ‘[Dec]’ with actual type ‘Type’
    • In the third argument of ‘InstanceD’, namely
        ‘(ConT ''M.MVector `AppT` ConT ''MVector `AppT` typ)’
      In the expression:
        InstanceD
          Nothing cxts (ConT ''M.MVector `AppT` ConT ''MVector `AppT` typ)
      In the expression:
        InstanceD
          Nothing cxts (ConT ''M.MVector `AppT` ConT ''MVector `AppT` typ)
        $ concat
            [wrap 'M.basicLength [mv] id,
             wrap 'M.basicUnsafeSlice [i, n, ....] (AppE mvCon),
             wrap 'M.basicOverlaps [mv, mv'] id,
             wrap 'M.basicUnsafeNew [n] (liftE mvCon), ....]

Data/Vector/Unboxed/Deriving.hs:153:26: error:
    • Couldn't match expected type ‘[Dec] -> Dec’
                  with actual type ‘Dec’
    • The first argument of ($) takes one argument,
      but its type ‘Dec’ has none
      In the expression:
        InstanceD
          Nothing cxts (ConT ''G.Vector `AppT` ConT ''Vector `AppT` typ)
        $ concat
            [wrap 'G.basicUnsafeFreeze [mv] (liftE vCon),
             wrap 'G.basicUnsafeThaw [v] (liftE mvCon),
             wrap 'G.basicLength [v] id,
             wrap 'G.basicUnsafeSlice [i, n, ....] (AppE vCon), ....]
      In an equation for ‘instanceVector’:
          instanceVector
            = InstanceD
                Nothing cxts (ConT ''G.Vector `AppT` ConT ''Vector `AppT` typ)
              $ concat
                  [wrap 'G.basicUnsafeFreeze [mv] (liftE vCon),
                   wrap 'G.basicUnsafeThaw [v] (liftE mvCon),
                   wrap 'G.basicLength [v] id, ....]

Data/Vector/Unboxed/Deriving.hs:153:36: error:
    • Couldn't match type ‘Maybe a1’ with ‘[Pred]’
      Expected type: Cxt
        Actual type: Maybe a1
    • In the first argument of ‘InstanceD’, namely ‘Nothing’
      In the expression:
        InstanceD
          Nothing cxts (ConT ''G.Vector `AppT` ConT ''Vector `AppT` typ)
      In the expression:
        InstanceD
          Nothing cxts (ConT ''G.Vector `AppT` ConT ''Vector `AppT` typ)
        $ concat
            [wrap 'G.basicUnsafeFreeze [mv] (liftE vCon),
             wrap 'G.basicUnsafeThaw [v] (liftE mvCon),
             wrap 'G.basicLength [v] id,
             wrap 'G.basicUnsafeSlice [i, n, ....] (AppE vCon), ....]

Data/Vector/Unboxed/Deriving.hs:153:44: error:
    • Couldn't match type ‘[Pred]’ with ‘Type’
      Expected type: Type
        Actual type: Cxt
    • In the second argument of ‘InstanceD’, namely ‘cxts’
      In the expression:
        InstanceD
          Nothing cxts (ConT ''G.Vector `AppT` ConT ''Vector `AppT` typ)
      In the expression:
        InstanceD
          Nothing cxts (ConT ''G.Vector `AppT` ConT ''Vector `AppT` typ)
        $ concat
            [wrap 'G.basicUnsafeFreeze [mv] (liftE vCon),
             wrap 'G.basicUnsafeThaw [v] (liftE mvCon),
             wrap 'G.basicLength [v] id,
             wrap 'G.basicUnsafeSlice [i, n, ....] (AppE vCon), ....]

Data/Vector/Unboxed/Deriving.hs:154:14: error:
    • Couldn't match expected type ‘[Dec]’ with actual type ‘Type’
    • In the third argument of ‘InstanceD’, namely
        ‘(ConT ''G.Vector `AppT` ConT ''Vector `AppT` typ)’
      In the expression:
        InstanceD
          Nothing cxts (ConT ''G.Vector `AppT` ConT ''Vector `AppT` typ)
      In the expression:
        InstanceD
          Nothing cxts (ConT ''G.Vector `AppT` ConT ''Vector `AppT` typ)
        $ concat
            [wrap 'G.basicUnsafeFreeze [mv] (liftE vCon),
             wrap 'G.basicUnsafeThaw [v] (liftE mvCon),
             wrap 'G.basicLength [v] id,
             wrap 'G.basicUnsafeSlice [i, n, ....] (AppE vCon), ....]

Data/Vector/Unboxed/Deriving.hs:163:14: error:
    • Couldn't match expected type ‘[t0] -> Dec’ with actual type ‘Dec’
    • The function ‘InstanceD’ is applied to four arguments,
      but its type ‘Cxt -> Type -> [Dec] -> Dec’ has only three
      In the expression:
        InstanceD Nothing cxts (ConT ''Unbox `AppT` typ) []
      In the first argument of ‘return’, namely
        ‘[InstanceD Nothing cxts (ConT ''Unbox `AppT` typ) [],
          newtypeMVector, instanceMVector, newtypeVector, ....]’

Data/Vector/Unboxed/Deriving.hs:163:24: error:
    • Couldn't match type ‘Maybe a2’ with ‘[Pred]’
      Expected type: Cxt
        Actual type: Maybe a2
    • In the first argument of ‘InstanceD’, namely ‘Nothing’
      In the expression:
        InstanceD Nothing cxts (ConT ''Unbox `AppT` typ) []
      In the first argument of ‘return’, namely
        ‘[InstanceD Nothing cxts (ConT ''Unbox `AppT` typ) [],
          newtypeMVector, instanceMVector, newtypeVector, ....]’

Data/Vector/Unboxed/Deriving.hs:163:32: error:
    • Couldn't match type ‘[Pred]’ with ‘Type’
      Expected type: Type
        Actual type: Cxt
    • In the second argument of ‘InstanceD’, namely ‘cxts’
      In the expression:
        InstanceD Nothing cxts (ConT ''Unbox `AppT` typ) []
      In the first argument of ‘return’, namely
        ‘[InstanceD Nothing cxts (ConT ''Unbox `AppT` typ) [],
          newtypeMVector, instanceMVector, newtypeVector, ....]’

Data/Vector/Unboxed/Deriving.hs:163:38: error:
    • Couldn't match expected type ‘[Dec]’ with actual type ‘Type’
    • In the third argument of ‘InstanceD’, namely
        ‘(ConT ''Unbox `AppT` typ)’
      In the expression:
        InstanceD Nothing cxts (ConT ''Unbox `AppT` typ) []
      In the first argument of ‘return’, namely
        ‘[InstanceD Nothing cxts (ConT ''Unbox `AppT` typ) [],
          newtypeMVector, instanceMVector, newtypeVector, ....]’
cabal: Error: some packages failed to install:
vector-th-unbox-0.2.1.6 failed during the building phase. The exception was:
ExitFailure 1
Creating sandbox for transformers-compat-0.5.1.4-0f42286ab8895bc6d8dff04553e432d0948c3244
Warning:
/var/folders/v8/mpmmts8946j10dzhv2gxvt1h0000gp/T/pkgConf-mwc-random-0.13.4178448449274243042.0:
Unrecognized field abi on line 29
Installed mwc-random-0.13.4.0
Creating sandbox for vector-th-unbox-0.2.1.6-8e146e7c83bb8edcaa204ad481dff5ee2f6d99d6
Creating sandbox for parallel-3.2.1.0-d82a69354254d52bcbb0abb24ff2d7b11a34bc78
Failed to install vector-th-unbox-0.2.1.6
Process failed: cabal install --ghc-options=-j4 --max-backjumps=0 vector-th-unbox-0.2.1.6 --constraint primitive == 0.6.1.0 --constraint vector == 0.11.0.0 --constraint vector-th-unbox == 0.2.1.6 (exit code: 1)
criterion-1.1.1.0
 └─╼ statistics-0.13.2.3
      └─╼ math-functions-0.1.6.0
           └─╼ vector-th-unbox-0.2.1.6
math-functions-0.1.6.0
 └─╼ vector-th-unbox-0.2.1.6
statistics-0.13.2.3
 └─╼ math-functions-0.1.6.0
      └─╼ vector-th-unbox-0.2.1.6
vector-th-unbox-0.2.1.6
```

**Comment by newhoggy** [comment]
Looks like I've managed to reproduce the error:

```
[nix-shell:~/wrk/haskell-works/hw-all/hw-prim]$ cabal build
Building hw-prim-0.0.0.13...
Preprocessing library hw-prim-0.0.0.13...

on the commandline: warning:
    -this-package-key is deprecated: Use -this-unit-id instead
[ 1 of 11] Compiling HaskellWorks.Data.Vector.StorableVectorLike ( src/HaskellWorks/Data/Vector/StorableVectorLike.hs, dist/build/HaskellWorks/Data/Vector/StorableVectorLike.o )

src/HaskellWorks/Data/Vector/StorableVectorLike.hs:14:3: error:
    • Could not deduce (StorableVectorLike v e0)
      from the context: (StorableVectorLike v e, Storable a, Storable b)
        bound by the type signature for:
                   sImap :: (StorableVectorLike v e, Storable a, Storable b) =>
                            (Int -> a -> b) -> v a -> v b
        at src/HaskellWorks/Data/Vector/StorableVectorLike.hs:14:3-68
      The type variable ‘e0’ is ambiguous
    • In the ambiguity check for ‘sImap’
      To defer the ambiguity check to use sites, enable AllowAmbiguousTypes
      When checking the class method:
        sImap :: forall (v :: * -> *) e.
                 StorableVectorLike v e =>
                 forall a b.
                 (Storable a, Storable b) =>
                 (Int -> a -> b) -> v a -> v b
      In the class declaration for ‘StorableVectorLike’

src/HaskellWorks/Data/Vector/StorableVectorLike.hs:15:3: error:
    • Could not deduce (StorableVectorLike v e0)
      from the context: (StorableVectorLike v e, Storable a, Storable b)
        bound by the type signature for:
                   sMap :: (StorableVectorLike v e, Storable a, Storable b) =>
                           (a -> b) -> v a -> v b
        at src/HaskellWorks/Data/Vector/StorableVectorLike.hs:15:3-60
      The type variable ‘e0’ is ambiguous
    • In the ambiguity check for ‘sMap’
      To defer the ambiguity check to use sites, enable AllowAmbiguousTypes
      When checking the class method:
        sMap :: forall (v :: * -> *) e.
                StorableVectorLike v e =>
                forall a b. (Storable a, Storable b) => (a -> b) -> v a -> v b
      In the class declaration for ‘StorableVectorLike’

src/HaskellWorks/Data/Vector/StorableVectorLike.hs:16:3: error:
    • Could not deduce (StorableVectorLike v e0)
      from the context: (StorableVectorLike v e, Storable a)
        bound by the type signature for:
                   sUnfoldr :: (StorableVectorLike v e, Storable a) =>
                               (b -> Maybe (a, b)) -> b -> v a
        at src/HaskellWorks/Data/Vector/StorableVectorLike.hs:16:3-61
      The type variable ‘e0’ is ambiguous
    • In the ambiguity check for ‘sUnfoldr’
      To defer the ambiguity check to use sites, enable AllowAmbiguousTypes
      When checking the class method:
        sUnfoldr :: forall (v :: * -> *) e.
                    StorableVectorLike v e =>
                    forall a b. Storable a => (b -> Maybe (a, b)) -> b -> v a
      In the class declaration for ‘StorableVectorLike’

src/HaskellWorks/Data/Vector/StorableVectorLike.hs:17:3: error:
    • Could not deduce (StorableVectorLike v e0)
      from the context: (StorableVectorLike v e, Storable a)
        bound by the type signature for:
                   sUnfoldrN :: (StorableVectorLike v e, Storable a) =>
                                Int -> (b -> Maybe (a, b)) -> b -> v a
        at src/HaskellWorks/Data/Vector/StorableVectorLike.hs:17:3-69
      The type variable ‘e0’ is ambiguous
    • In the ambiguity check for ‘sUnfoldrN’
      To defer the ambiguity check to use sites, enable AllowAmbiguousTypes
      When checking the class method:
        sUnfoldrN :: forall (v :: * -> *) e.
                     StorableVectorLike v e =>
                     forall a b. Storable a => Int -> (b -> Maybe (a, b)) -> b -> v a
      In the class declaration for ‘StorableVectorLike’
[ 2 of 11] Compiling HaskellWorks.Data.Vector.BoxedVectorLike ( src/HaskellWorks/Data/Vector/BoxedVectorLike.hs, dist/build/HaskellWorks/Data/Vector/BoxedVectorLike.o )

src/HaskellWorks/Data/Vector/BoxedVectorLike.hs:14:3: error:
    • Could not deduce (BoxedVectorLike v e0)
      from the context: BoxedVectorLike v e
        bound by the type signature for:
                   bImap :: BoxedVectorLike v e => (Int -> a -> b) -> v a -> v b
        at src/HaskellWorks/Data/Vector/BoxedVectorLike.hs:14:3-40
      The type variable ‘e0’ is ambiguous
    • In the ambiguity check for ‘bImap’
      To defer the ambiguity check to use sites, enable AllowAmbiguousTypes
      When checking the class method:
        bImap :: forall (v :: * -> *) e.
                 BoxedVectorLike v e =>
                 forall a b. (Int -> a -> b) -> v a -> v b
      In the class declaration for ‘BoxedVectorLike’

src/HaskellWorks/Data/Vector/BoxedVectorLike.hs:15:3: error:
    • Could not deduce (BoxedVectorLike v e0)
      from the context: BoxedVectorLike v e
        bound by the type signature for:
                   bMap :: BoxedVectorLike v e => (a -> b) -> v a -> v b
        at src/HaskellWorks/Data/Vector/BoxedVectorLike.hs:15:3-32
      The type variable ‘e0’ is ambiguous
    • In the ambiguity check for ‘bMap’
      To defer the ambiguity check to use sites, enable AllowAmbiguousTypes
      When checking the class method:
        bMap :: forall (v :: * -> *) e.
                BoxedVectorLike v e =>
                forall a b. (a -> b) -> v a -> v b
      In the class declaration for ‘BoxedVectorLike’

src/HaskellWorks/Data/Vector/BoxedVectorLike.hs:16:3: error:
    • Could not deduce (BoxedVectorLike v e0)
      from the context: (BoxedVectorLike v e, Storable a)
        bound by the type signature for:
                   bUnfoldr :: (BoxedVectorLike v e, Storable a) =>
                               (b -> Maybe (a, b)) -> b -> v a
        at src/HaskellWorks/Data/Vector/BoxedVectorLike.hs:16:3-61
      The type variable ‘e0’ is ambiguous
    • In the ambiguity check for ‘bUnfoldr’
      To defer the ambiguity check to use sites, enable AllowAmbiguousTypes
      When checking the class method:
        bUnfoldr :: forall (v :: * -> *) e.
                    BoxedVectorLike v e =>
                    forall a b. Storable a => (b -> Maybe (a, b)) -> b -> v a
      In the class declaration for ‘BoxedVectorLike’

src/HaskellWorks/Data/Vector/BoxedVectorLike.hs:17:3: error:
    • Could not deduce (BoxedVectorLike v e0)
      from the context: (BoxedVectorLike v e, Storable a)
        bound by the type signature for:
                   bUnfoldrN :: (BoxedVectorLike v e, Storable a) =>
                                Int -> (b -> Maybe (a, b)) -> b -> v a
        at src/HaskellWorks/Data/Vector/BoxedVectorLike.hs:17:3-69
      The type variable ‘e0’ is ambiguous
    • In the ambiguity check for ‘bUnfoldrN’
      To defer the ambiguity check to use sites, enable AllowAmbiguousTypes
      When checking the class method:
        bUnfoldrN :: forall (v :: * -> *) e.
                     BoxedVectorLike v e =>
                     forall a b. Storable a => Int -> (b -> Maybe (a, b)) -> b -> v a
      In the class declaration for ‘BoxedVectorLike’
[ 3 of 11] Compiling HaskellWorks.Data.Search ( src/HaskellWorks/Data/Search.hs, dist/build/HaskellWorks/Data/Search.o )
[ 4 of 11] Compiling HaskellWorks.Data.Positioning ( src/HaskellWorks/Data/Positioning.hs, dist/build/HaskellWorks/Data/Positioning.o )
[ 5 of 11] Compiling HaskellWorks.Data.TreeCursor ( src/HaskellWorks/Data/TreeCursor.hs, dist/build/HaskellWorks/Data/TreeCursor.o )
[ 6 of 11] Compiling HaskellWorks.Data.Vector.VectorLike ( src/HaskellWorks/Data/Vector/VectorLike.hs, dist/build/HaskellWorks/Data/Vector/VectorLike.o )
[ 7 of 11] Compiling HaskellWorks.Data.FromForeignRegion ( src/HaskellWorks/Data/FromForeignRegion.hs, dist/build/HaskellWorks/Data/FromForeignRegion.o )
[ 8 of 11] Compiling HaskellWorks.Data.FromByteString ( src/HaskellWorks/Data/FromByteString.hs, dist/build/HaskellWorks/Data/FromByteString.o )
[ 9 of 11] Compiling HaskellWorks.Data.Decode ( src/HaskellWorks/Data/Decode.hs, dist/build/HaskellWorks/Data/Decode.o )
[10 of 11] Compiling HaskellWorks.Data.Char.IsChar ( src/HaskellWorks/Data/Char/IsChar.hs, dist/build/HaskellWorks/Data/Char/IsChar.o )
[11 of 11] Compiling HaskellWorks.Data.ByteString ( src/HaskellWorks/Data/ByteString.hs, dist/build/HaskellWorks/Data/ByteString.o )
```

**Comment by newhoggy** [comment]
I've update the metadata for the package from the matrix page you posted.  I'm unable to queue a build though.  It is rejecting my hackage credentials.

**Comment by newhoggy** [comment]
I have published new versions that build.  Am I okay to close this ticket?

**Comment by hvr** [comment]
The matrix.h.h.o page isn't integrated yet with hackage.h.o sign-on. This will be possible at some point though. And yeah, this ticket can be closed. I'll fixup the `0.0.0.*` versions later today, as their meta-data is still incorrect.

**Comment by newhoggy** [comment]
Thanks!
